import requests
import pandas as pd
import os

cateogry = 'home'

# Load the CSV file generated by the Google Apps Script
csv_file = '/Users/taro/Downloads/productionDownloadUrls_gbh_home.csv'
output_folder = 'images_gbh_home'

# Create the output folder if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Read the CSV file
df = pd.read_csv(csv_file)

# Filter out skipped SKUs
df = df[df['Skipped'] != 'Yes']

# Skip error
print('Skipping SKUs with spreadsheet link error:')
for sku in df[df['Download URL'].isnull()]['Product'].tolist():
    print(sku)
df = df[df['Download URL'].notnull()]
    


# Dictionary to keep track of sequential suffixes for each product
product_counters = {}

def get_output_image_name(product, image_name):
    # Function to determine the output image name
    if image_name in ['a.jpg', 'b.jpg']:
        return f'{product}__{image_name}'
    product_counters.setdefault(product, 1)
    product_counters[product] += 1
    return f'{product}_{product_counters[product]:02}.jpg'

# Download each image
for index, row in df.iterrows():
    product = row['Product']
    image_name = row['Image Name']
    download_url = row['Download URL']

    print(f'processing {product}, {image_name}')

    # Download the image
    response = requests.get(download_url, stream=True)
    if response.status_code == 200:
        output_image_name = get_output_image_name(product, image_name)
        with open(os.path.join(output_folder, output_image_name), 'wb') as f:
            for chunk in response.iter_content(1024):
                f.write(chunk)
    else:
        print(f"Failed to download {image_name} from {download_url}")

print("Download completed!")
