import requests
import pandas as pd
import os

# Load the CSV file generated by the Google Apps Script
csv_file = '/Users/taro/Downloads/downloadUrls.csv'
output_folder = 'images_kume_20240801'

missed_images_dir = '/Users/taro/sc/playground/images_kume_20240731/missed'
missed_skus = set([p.rsplit('_')[0] for p in os.listdir(missed_images_dir)])

print('going to reprocess:')
for sku in missed_skus:
    print(f'\t{sku}')

df = pd.read_csv(csv_file)
df = df[df['Product'].isin(missed_skus)]

# Create the output folder if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Dictionary to keep track of sequential suffixes for each product
product_counters = {}

def get_output_image_name(product, image_name):
    # Function to determine the output image name
    product_counters.setdefault(product, 0)
    product_counters[product] += 1
    ext = image_name.rsplit('.', 1)[-1]
    return f'{product}_{product_counters[product]:02}.{ext}'

# Download each image
for index, row in df.iterrows():
    product = row['Product']
    image_name = row['Image Name']
    download_url = row['Download URL']

    print(f'processing {product}, {image_name}')

    # Download the image
    response = requests.get(download_url, stream=True)
    if response.status_code == 200:
        output_image_name = get_output_image_name(product, image_name)
        with open(os.path.join(output_folder, output_image_name), 'wb') as f:
            for chunk in response.iter_content(1024):
                f.write(chunk)
    else:
        print(f"Failed to download {image_name} from {download_url}")

print("Download completed!")
